### ISSUE TITLE
Cannot type into editable text field

### ISSUE THREAD

**Issue by jonathan-beebe** [kgn/KGModal#2]
I have an editable UITextField in my contentView. If I add this view to the main ViewController it's editable as expected.

If I add the view to the KGModal shared instance it will accept a mouse click and the cursor appears along with the keyboard, but I cannot type into the text field.

I have not been able to isolate the issue, but it appears to be, at least in part, because of something in the KGModal class.

**Comment by jinjuezhou** [comment]
this bug is still here!
